openapi: 3.0.0
info:
  title: Tarifs API
  description: This API manage the tarifs
  version: 1.0.0
servers:
  - url: www.github.com
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /tarifs:
    get:
      summary: Returns a list of tarifs.
      description: donne la liste des tous les tarifs
      responses:
        '200':    # status code
          description: A list of tarifs
          content:
            application/json:
              schema: 
               $ref: "#/components/schemas/TarifsResources" 
        '400':
          description: Bad request. The request was malformed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        '404':
          description: Not found. The requested resource did not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"       
  /tarifs/terrain:
    get:
      summary: Returns a list of tarifs.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/TarifsResources"
        '400':
          description: Bad request. The request was malformed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        '404':
          description: Not found. The requested resource did not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"      
                              
components:
  schemas:
  
    Error:
      properties:
        uuid:
          type: string
          example: "65adc8f3-28e5-4772-8d1f-109616b01ae8"
        exceptionType:
          type: string
          example: "ResourceNotFoundException"
        message:
          type: string
          example: "Error message"   
    TarifsResources:
      type: array
      items:
        $ref: "#/components/schemas/TarifResource"
    TarifResource:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1          # Property example
        name:
          type: string
          example: tarif soir   # tarif soir
        prix:  
          type: number
          example: 10.0
        startDate:
          type: string
          format: date
          example: 23-02-2020
        endDate:
          type: string
          format: date
          example: 23-02-2020
        startTime:
          type: string
          format: time
          example: 00:00
        endTime:
          type: string
          format: time
          example: 00:00  
        weekend:
          type: boolean
          example: true
        actif:
          type: boolean
          example: true
        specialTarif:
          type: boolean
          example: true
        defaultTarif:
          type: boolean
          example: true  
        
     
          
          
          
          

        
    
    
                      
                  